name: "Test GH Token"
description: "Test if GitHub token is passed correctly"

inputs:
  gh-token:
    description: "GitHub token to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Print token
      shell: bash
      run: |
        echo "${{ inputs.gh-token }}"
